- name: get docker info
  command: docker info
  register: swarm_docker_info
  changed_when: False
  tags:
  - skip_ansible_lint

- name: Start first swarm manager
  command: docker swarm init
  when: "swarm_docker_info.stdout.find('Swarm: active') == -1
    and inventory_hostname == groups['swarm_managers'][0]"
  tags:
    - skip_ansible_lint

- name: get manager token
  changed_when: False
  command: docker swarm join-token -q manager
  register: swarm_manager_token
  delegate_to: "{{ groups['swarm_managers'][0] }}"
  delegate_facts: True
  when: "inventory_hostname != groups['swarm_managers'][0]"
  tags:
  - skip_ansible_lint

- name: join to swarm as manager
  command: docker swarm join --token "{{ swarm_manager_token.stdout }}" "{{ groups['swarm_managers'][0]}}":"{{ swarm_manager_port}}"
  when: "inventory_hostname != groups['swarm_managers'][0]
    and swarm_docker_info.stdout.find('Swarm: active') == -1"
  tags:
  - skip_ansible_lint
